### ISSUE TITLE
can not find the lino.msg file

### ISSUE THREAD

**Issue by David-Guo** [grassjelly/lino_pid#1]
Hi, I can not find the lino.msg file to generate header file lino_msgs/PID.h , is there any help ?

**Comment by grassjelly** [comment]
You need to download and build https://github.com/grassjelly/lino_msgs .You can check out the whole documentation here: linorobot.org

**Comment by grassjelly** [comment]
@David-Guo have you solved this?

**Comment by David-Guo** [comment]
@grassjelly yes, it's very useful, thank you!

**Comment by grassjelly** [comment]
@David-Guo alright man! 👍🏻
